---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: homework4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: homework4
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: homework4
    spec:
      initContainers:
      - image: busybox
        name: mount-permissions-fix
        command: ["sh", "-c", "chmod 777 /var/lib/postgresql/data"]
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      containers:
      - image: postgres:10.13
        name: postgres
        ports:
        - containerPort: 5432
        env:
          - name: secret
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: PASS
        volumeMounts:
        - name: data
          mountPath: /var/lib/postgresql/data
      volumes:
        - name: data
        persistentVolumeClaim:
          claimName: homework4
